title:              Yjin's Blog             
description:        A Blog Theme by Start Bootstrap
# author:             yjin
baseurl:            ""
url:                "https://yjin-leee.github.io"

# Social Profiles
twitter_username:   
github_username:    yjin-leee
facebook_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# Authors
authors:
  sal:
    name: yjin-leee
    display_name: yjin
    gravatar: 
    email: yjin.lee@kakao.com
    web: https://yjin-leee.github.io
    # twitter: https://twitter.com/username
